### ISSUE TITLE
Properly handle class members with decorators

### ISSUE THREAD

**Issue by bo4arovpavel1989** [timocov/ts-transformer-properties-rename#31]
The goal of this package is to mangle renamed properties by minifiers like 'terser', but there is an issue, when using class members with decorators. When transformer renames decorated class member with prefix, this class member is mangled by minifier, but it can't handle connection of this class member and decorator function.
Ommiting implementation of `__decorate` fn, decorator transform has the following output
```ts
// input
class Foo {
  @foo private field = 1;
}

// output
class Foo {
    constructor() {
        this.field = 1;
    }
}
__decorate([
    foo
], Foo.prototype, "field", void 0);

```
If use ts-transformer-properties-rename package, it will be transformed to
```ts
// input
class Foo {
  @foo private _private_field = 1;
}

// output
class Foo {
    constructor() {
        this._private_field = 1;
    }
}
__decorate([
    foo
], Foo.prototype, "_private_field", void 0);

```
But after terser's mangling it will be smth like that
```ts
// input
class Foo {
  @foo private i = 1;
}

// output
class Foo {
    constructor() {
        this.i = 1;
    }
}
__decorate([
    foo
], Foo.prototype, "_private_field", void 0);

```
There is an [issue](https://github.com/terser/terser/issues/1075) in terser repo, where contributors assumed, that it could be solved by mangling string literals by same prefix as well, but according [issue](https://github.com/terser/terser/issues/990) is still unresolved

**Comment by timocov** [comment]
Not too sure about whether an option should be enabled by default (or whether this should should exist at all as I haven't worked with decorators close enough), but now at least it would be possible to disable renaming for decorated fields by enabling option `ignoreDecorated`, see 0c348838b6723a62b0f234f5e14d34da5d3891e8. Feel free to share feedback here or create another issue if you find anything else.

**Comment by timocov** [comment]
The fix has been released in https://github.com/timocov/ts-transformer-properties-rename/releases/tag/v0.14.0 (please pay attention on breaking changes in this release).
